### ISSUE TITLE
"Archived" content is present in my exported data

### ISSUE THREAD

**Issue by chestercharles** [contentful/contentful-cli#221] opened 2020-02-10 18:51 UTC
## Expected Behavior

Content with an "Archived" status **is not** exported.

## Actual Behavior

Content with an "Archived" status **is** exported.

## Steps to Reproduce

1. Export data using this export config:
```
{
  "space-id": "vf02apkj6wr7",
  "content-file": "contentful-export.json",
  "include-drafts": false,
  "skip-content-model": false,
  "skip-webhooks": true,
  "skip-roles": true,
  "content-only": true,
  "save-file": true,
  "error-log-file": "contentful-export-error-log.json",
  "download-assets": false
}
```

## Context

This might be more of a question rather than an issue, but I could not find an answer in the documentation. When exporting from an environment with the configuration above, should I expect "Archived" status content to be exported?

## Environment

-   **Language Version**: v12.14.0
-   **Package Manager Version**: 6.13.4
-   **Browser Version**: N/A
-   **Operating System**: macOS Catalina v10.15.3
-   **Package Version**: 1.1.1

**Comment by OriginalEXE** [comment] 2020-02-13 14:09
Hello,

I just tested this locally and was not able to reproduce it using our CLI.

The archived entries should only be included when using the `--include-archived` flag. You can try setting it explicitly to `false` in your config, though it should not be necessary (`false` is the default value).

**Comment by makinwab** [comment] 2020-04-02 15:30
Thanks for the response, @OriginalEXE. 

I'll be closing this issue, if there's need to re-open please feel free.

**Closed by makinwab** 2020-04-02 15:30 UTC
